spark.jars.packages		io.delta:delta-core_2.12:2.4.0,org.apache.hadoop:hadoop-aws:3.3.2
spark.sql.extensions		io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog	org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.warehouse.dir		s3a://ecommerce-pooja/pipeline/warehouse
spark.driver.extraJavaOptions 	-Dderby.system.home=/data/metastore
spark.sql.catalogImplementation hive
spark.hadoop.fs.s3a.aws.credentials.provider      com.amazonaws.auth.EnvironmentVariableCredentialsProvider